import type { AppErrorPolicyMap } from '../api/parseAxiosError';

/**
 * 서버에서 내려주는 에러 코드의 집합
 * - 반드시 백엔드 ErrorCode 와 1:1로 맞춘다
 */
export type ServerErrorCode =
  // ===== 공통 =====
  | 'INVALID_INPUT_VALUE'
  | 'INTERNAL_SERVER_ERROR'
  | 'PRESIGNED_URL_GENERATION_FAILED'
  | 'FILE_MOVE_FAILED'
  | 'EMAIL_SENDING_FAILURE'
  // ===== 인증 / 인가 =====
  | 'INVALID_TOKEN'
  | 'EXPIRED_TOKEN'
  | 'UNAUTHORIZED_USER'
  | 'TOKEN_NOT_FOUND'
  | 'REFRESH_TOKEN_NOT_FOUND'
  | 'REFRESH_TOKEN_MISMATCH'
  | 'AUTHORIZATION_HEADER_MISSING'
  | 'TOKEN_AUTHENTICATION_FAILED'
  // ===== 회원 =====
  | 'LOGIN_FAILED'
  | 'PASSWORD_NOT_MATCH'
  | 'EMAIL_DUPLICATION'
  | 'SAME_EMAIL_AS_CURRENT'
  | 'NICKNAME_DUPLICATION'
  | 'TARGET_USER_NOT_FOUND'
  | 'USER_NOT_FOUND'
  | 'USER_NOT_FOUND_FOR_RESET'
  | 'INVALID_PASSWORD'
  | 'PASSWORD_AUTHENTICATION_FAILED'
  | 'SAME_PASSWORD_NOT_ALLOWED'
  | 'UPDATE_FAILED'
  | 'SOCIAL_KAKAO_USER_CANNOT_RESET_PASSWORD'
  | 'SOCIAL_GOOGLE_USER_CANNOT_RESET_PASSWORD'
  | 'VERIFICATION_CODE_EXPIRED'
  | 'VERIFICATION_CODE_RESEND_LIMIT'
  | 'VERIFICATION_CODE_MISMATCH'
  | 'VERIFICATION_CODE_FAILURE_LIMIT';

/**
 * 프론트 전역에서 사용하는 표준 에러 객체
 */
export interface AppError {
  code?: ServerErrorCode;
  AppErrorPolicyMap: AppErrorPolicyMap;
}
